/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as ToReadListRouteImport } from './routes/to-read-list';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as NotificationsRouteImport } from './routes/notifications';
import { Route as LoginRouteImport } from './routes/login';
import { Route as DebugLogsRouteImport } from './routes/debug-logs';
import { Route as CreateReviewRouteImport } from './routes/create-review';
import { Route as IndexRouteImport } from './routes/index';
import { Route as SearchIndexRouteImport } from './routes/search/index';
import { Route as UserUserIdRouteImport } from './routes/user/$userId';
import { Route as SearchUsersRouteImport } from './routes/search/users';
import { Route as SearchReviewsRouteImport } from './routes/search/reviews';
import { Route as SearchBooksRouteImport } from './routes/search/books';
import { Route as ReviewReviewIdRouteImport } from './routes/review/$reviewId';
import { Route as BookBookIdRouteImport } from './routes/book/$bookId';
import { Route as UserUserIdFollowingRouteImport } from './routes/user/$userId.following';
import { Route as UserUserIdFollowersRouteImport } from './routes/user/$userId.followers';
const ToReadListRoute = ToReadListRouteImport.update({
    id: '/to-read-list',
    path: '/to-read-list',
    getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => rootRouteImport,
});
const ResetPasswordRoute = ResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const OnboardingRoute = OnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const DebugLogsRoute = DebugLogsRouteImport.update({
    id: '/debug-logs',
    path: '/debug-logs',
    getParentRoute: () => rootRouteImport,
});
const CreateReviewRoute = CreateReviewRouteImport.update({
    id: '/create-review',
    path: '/create-review',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const SearchIndexRoute = SearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => rootRouteImport,
});
const UserUserIdRoute = UserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => rootRouteImport,
});
const SearchUsersRoute = SearchUsersRouteImport.update({
    id: '/search/users',
    path: '/search/users',
    getParentRoute: () => rootRouteImport,
});
const SearchReviewsRoute = SearchReviewsRouteImport.update({
    id: '/search/reviews',
    path: '/search/reviews',
    getParentRoute: () => rootRouteImport,
});
const SearchBooksRoute = SearchBooksRouteImport.update({
    id: '/search/books',
    path: '/search/books',
    getParentRoute: () => rootRouteImport,
});
const ReviewReviewIdRoute = ReviewReviewIdRouteImport.update({
    id: '/review/$reviewId',
    path: '/review/$reviewId',
    getParentRoute: () => rootRouteImport,
});
const BookBookIdRoute = BookBookIdRouteImport.update({
    id: '/book/$bookId',
    path: '/book/$bookId',
    getParentRoute: () => rootRouteImport,
});
const UserUserIdFollowingRoute = UserUserIdFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => UserUserIdRoute,
});
const UserUserIdFollowersRoute = UserUserIdFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => UserUserIdRoute,
});
const UserUserIdRouteChildren = {
    UserUserIdFollowersRoute: UserUserIdFollowersRoute,
    UserUserIdFollowingRoute: UserUserIdFollowingRoute,
};
const UserUserIdRouteWithChildren = UserUserIdRoute._addFileChildren(UserUserIdRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    CreateReviewRoute: CreateReviewRoute,
    DebugLogsRoute: DebugLogsRoute,
    LoginRoute: LoginRoute,
    NotificationsRoute: NotificationsRoute,
    OnboardingRoute: OnboardingRoute,
    ProfileRoute: ProfileRoute,
    RegisterRoute: RegisterRoute,
    ResetPasswordRoute: ResetPasswordRoute,
    SettingsRoute: SettingsRoute,
    ToReadListRoute: ToReadListRoute,
    BookBookIdRoute: BookBookIdRoute,
    ReviewReviewIdRoute: ReviewReviewIdRoute,
    SearchBooksRoute: SearchBooksRoute,
    SearchReviewsRoute: SearchReviewsRoute,
    SearchUsersRoute: SearchUsersRoute,
    UserUserIdRoute: UserUserIdRouteWithChildren,
    SearchIndexRoute: SearchIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
